### ISSUE TITLE
PR-curve with the complete negative test sample

### ISSUE THREAD

**Issue by songkq** [NathanUA/Binary-Segmentation-Evaluation-Tool#1]
Greeting!
If there are some test samples without a salient object in the image,  does it need to contain these samples when computing the PR-curve?  Since the precision and recall keep zero with any threshold.

**Comment by xuebinqin** [comment]
Although the precision and recall on these images without foregrounds are ill defined, we didn’t explicitly exclude them when computing the measures. Their measures should be zeros due to the 1e-8 used in the denominator or precision and recall computation.

**Comment by songkq** [comment]
@NathanUA Thanks for your reply. I wonder it  is reasonable to compute the average PR from the sum of each image? Why not to directly compute the PR from the whole dataset?
