### ISSUE TITLE
How can multiple algorithms be implemented in one graph?

### ISSUE THREAD

**Issue by z716315wm** [NathanUA/Binary-Segmentation-Evaluation-Tool#3]
Hello, author, I simply entered four data sets, but finally I got this error, how do I need to fix it?
![image](https://user-images.githubusercontent.com/70624857/92098853-5ae1ff00-ee0c-11ea-9263-0e0551e5be83.png)
![image](https://user-images.githubusercontent.com/70624857/92098924-7220ec80-ee0c-11ea-9af4-ae8a565ed7a1.png)

**Comment by xuebinqin** [comment]
you need to add additional line styles in line 21: lineSylClr = ['r-','b-'] # curve style, same size with rs_dirs.

**Comment by z716315wm** [comment]
Thanks NathanUA . The problem has been solved.
